import { type Metadata } from 'next'
import '../globals.css'
import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <ThemeProvider 
        attribute="class"
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange>
        {children}
        </ThemeProvider>
    </div>
  )
}