import { type Metadata } from 'next'
import '../globals.css'
import { SidebarFooter, SidebarProvider } from '@/components/ui/sidebar';
import  AppSidebar  from '@/components/AppSidebar';
import { ThemeProvider } from '@/components/ThemeProvider';

export const metadata: Metadata = {
  title: 'CMS CMLabs',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (   
    <ThemeProvider 
        attribute="class"
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange>
        {children}
    </ThemeProvider>
  )
}