import { type Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { ThemeProvider } from '@/components/ThemeProvider'

const NunitoSans = localFont({
  src: './fonts/NunitoSans.woff2',
  variable: '--font-nunito-sans',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: "CMS CMLABS",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${NunitoSans.variable} antialiased`}>
        <ThemeProvider 
          attribute="class"
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}